#!/bin/bash
exec 2>&1

exit_script() {
    echo "Shutdown!"
    CHILD_PID=$(cat /var/log/orkaudio/orkaudio.lock | head -n1)

    echo "Sending Kill to $CHILD_PID"
    trap - SIGINT SIGTERM # clear the trap
    kill -- $CHILD_PID # Sends SIGTERM to child/sub processes
    rm /var/log/orkaudio/orkaudio.lock
}

anywait(){
    for pid in "$@"; do
        while kill -0 "$pid"; do
            sleep 2
        done
    done
}

ulimit -n 65535

trap exit_script SIGINT SIGTERM

# exec chpst -u USER COMMAND
/usr/sbin/orkaudio

#wait 1 sec for child lock to be created.
sleep 1

CHILD_PID=$(cat /var/log/orkaudio/orkaudio.lock | head -n1 )

#watch on pid
echo "Starting Watch on $CHILD_PID"
while kill -0 $CHILD_PID 2> /dev/null; do sleep 1; done;
