#!/bin/bash
exec 2>&1

exit_script() {
    echo "Shutdown!"
    CHILD_PID=$(cat /var/log/orkaudio/orkaudio.lock)

    echo "Sending Kill to $CHILD_PID"
    trap - SIGINT SIGTERM # clear the trap
    kill -- $CHILD_PID # Sends SIGTERM to child/sub processes
}

anywait(){
    for pid in "$@"; do
        while kill -0 "$pid"; do
            sleep 2
        done
    done
}

trap exit_script SIGINT SIGTERM

# exec chpst -u USER COMMAND
/usr/sbin/orkaudio

#watch on pid
CHILD_PID=$(cat /var/log/orkaudio/orkaudio.lock)
while kill -0 $CHILD_PID 2> /dev/null; do sleep 1; done;
